input_file: '/clean_prm_sftData.json'
task_name: 'math'
file: 'math_500'
output_file: 'test'
openai_api_key: 'EMPTY'
openai_api_base: 'http://localhost:8002/v1'
propose_method: 'llama'
value_method: 'local'
mode: 'mcts'
temperature: 0.7
time_limit: null
iteration_limit: 8
roll_policy: 'greedy'
exploration_constant: 0.4
roll_forward_steps: 2
end_gate: 0.9
branch: 3
roll_branch: 1
inf: 0.8
evaluate: 'math'
alpha: 0.5
visualize: false
use_case_prompt: false
use_reflection: 'simple'
low: 0
high: 1
algorithm: 'dfs'
select_branch: 2
max_depth: 8
select_method: 'greedy'
consistency: true
VALUE_BASE_MODEL_DIR: 'peiyi9979/math-shepherd-mistral-7b-prm'
