algorithm: "PseudoAnswerGenerator_reasoning"

configs:
  system_prompt: ""
  input_key: "problem"
  response_key: "content"
  model_name: "deepseek-r1"
  url: 
  api_key: 
  db_path: "/root/workspace/culfjk4p420c73amv510/ywk/Text-Generator/examples/db/amc23_db.json"
  max_workers: 20
  max_times: 5
  output_file: "/root/workspace/culfjk4p420c73amv510/ywk/Text-Generator/examples/outputs/amc23_extract.jsonl"
  input_file: "/root/workspace/culfjk4p420c73amv510/ywk/Text-Generator/examples/data/amc23.jsonl"