algorithm: "PseudoAnswerGenerator"
configs:
  db_path: "/root/workspace/culfjk4p420c73amv510/ywk/Text-Generator/examples/db/amc23_db.json"
  output_file: "/root/workspace/culfjk4p420c73amv510/ywk/Text-Generator/examples/outputs/amc23_extract.jsonl"
  input_file: "/root/workspace/culfjk4p420c73amv510/ywk/Text-Generator/examples/data/amc23.jsonl"
  input_key: "problem"
  output_key: "content"
  max_times: 5
  generator_type: request
  request_model_generator:
    config:
      system_prompt: ""
      input_key: "problem"
      output_key: "content"
      model_name: "deepseek-r1"
      api_url: 
      api_key:
      db_path: "/root/workspace/culfjk4p420c73amv510/ywk/Text-Generator/examples/db/amc23_db.json"
      max_workers: 20
      output_file: "/root/workspace/culfjk4p420c73amv510/ywk/Text-Generator/examples/outputs/amc23_extract.jsonl"
      input_file: "/root/workspace/culfjk4p420c73amv510/ywk/Text-Generator/examples/data/amc23.jsonl"