input_file: "examples/data/amc23.jsonl"
output_file: "examples/data/amc23_synth.jsonl"
input_key: "question"
output_key: "generated_question"
generator_type: "request"
api_url: 
api_key: 
db_path : "examples/db/amc23_test.json"
max_workers: 100
model_name: "gpt-4o"
system_prompt: ""