input_file: "/root/workspace/culfjk4p420c73amv510/herunming/Text-Generator/examples/data/amc23.jsonl"
output_file: "/root/workspace/culfjk4p420c73amv510/herunming/Text-Generator/examples/outputs/amc23_output.jsonl"
input_key: "problem"
output_key: "solution"
algorithm: "AnswerGenerater_reasoning"

configs:
  system_prompt: ""
  input_key: "problem"
  model_name: "deepseek-r1"
  url: 
  api_key: 
  db_path: "/root/workspace/culfjk4p420c73amv510/herunming/Text-Generator/examples/db/amc23_db.json"
  max_workers: 20
  output_file: "/root/workspace/culfjk4p420c73amv510/herunming/Text-Generator/examples/outputs/amc23_output.jsonl"
  input_file: "/root/workspace/culfjk4p420c73amv510/herunming/Text-Generator/examples/data/amc23.jsonl"